detector_node:
  ros__parameters:
    onboard_detector:
      localization_mode: 0 # 0: pose (default) 1: odom

      # ROS Topics
      depth_image_topic: /camera1/rs1/depth/image_rect_raw
      color_image_topic: /camera1/rs1/color/image_raw
      lidar_pointcloud_topic: /velodyne_points
      pose_topic: /pose
      odom_topic: /odom
      use_tf_pose: true
      tf_map_frame: map
      tf_lidar_frame: velodyne
      tf_depth_frame: rs1_link_refined
      tf_color_frame: rs1_link_refined

      # Camera Parameters
      depth_intrinsics: [436.9647521972656, 436.9647521972656, 431.9205627441406, 240.13380432128906] # fx, fy, cx, cy - from actual camera calibration
      color_intrinsics: [645.0390014648438, 644.30419921875, 653.908203125, 365.65606689453125] # fx, fy, cx, cy
      depth_scale_factor: 1000.0 # 1000 for Intel Realsense Camera
      depth_min_value: 0.5
      depth_max_value: 5.0
      depth_filter_margin: 10 # filter
      depth_skip_pixel: 2  # filter
      image_cols: 848 #depth_image_width
      image_rows: 480 #depth_image_cols

      # System
      time_step: 0.033

      # DBSCAN Common
      ground_height: -0.2 # height of ground to remove ground points
      roof_height: 5.0 # relative height of roof to remove roof points

      # DBSCAN visual param
      voxel_occupied_thresh: 5.0 # min num of points for a voxel to be occupied in voxel filter
      dbscan_min_points_cluster: 20 # 20: 4.0m range; 30: 3.5m range 40: 3.0m range
      dbscan_search_range_epsilon: 0.05 # searching range radius

      # DBSCAN LiDAR param
      lidar_DBSCAN_min_points: 10
      lidar_DBSCAN_epsilon: 0.05
      downsample_threshold: 3500 # threshold for downsampling
      gaussian_downsample_rate: 6

      # LiDAR Visual Filtering
      filtering_BBox_IOU_threshold: 0.2

      # Tracking and data association
      max_match_range: 0.5 # max match range between time steps in meters
      max_size_diff_range: 0.5 #  in meter
      feature_weight: [3.0, 3.0, 0.1, 0.5, 0.5, 0.05, 0.0, 0.0, 0.0] # weight for feagent 3pos + 3size +  3 pc centroid
      history_size: 100 # size of tracking history. history[0] is current detection
      fix_size_history_threshold: 10 # History threshold (num of frames) to fix box size
      fix_size_dimension_threshold: 0.4 # dimension threshold (size of proportional) to fix box size
      kalman_filter_param: [0.25, 0.01, 0.05, 0.05, 0.04, 0.3, 0.6]
      kalman_filter_averaging_frames: 10

      # Classification
      frame_skip: 5 # num of frames skiped when comparing 2 point clouds
      dynamic_velocity_threshold: 0.2
      dynamic_voting_threshold: 0.8
      frames_force_dynamic: 10 # Range of searching dynamic obstacles in box history
      frames_force_dynamic_check_range: 30 # threshold for forcing dynamic obstacles
      dynamic_consistency_threshold: 15 # obstacles being voted as dynamic for continuous k frames are eligible to be classified as dynamic

      # Constrain size
      target_constrain_size: true
      target_object_size: [0.5, 0.5, 1.5]
      max_object_size: [3.0, 3.0, 2.0] # filter out objects that are too large

calibration_icp_node:
  ros__parameters:
    depth_topic: /camera1/rs1/depth/image_rect_raw
    velodyne_topic: /velodyne_points
    lidar_frame: velodyne
    camera_frame: rs1_link
    refined_camera_frame: rs1_link_refined
    icp_max_correspondence_distance: 0.2
    icp_max_iteration: 100
    icp_voxel_size: 0.05
    icp_use_point_to_plane: true
    icp_normal_radius: 0.15
    icp_normal_max_nn: 30
    min_overlap_points: 100
    overlap_fov_margin_px: 120
    onboard_detector:
      depth_intrinsics: [436.9647521972656, 436.9647521972656, 431.9205627441406, 240.13380432128906]
      depth_scale_factor: 1000.0
      depth_min_value: 0.5
      depth_max_value: 5.0
      depth_skip_pixel: 2

yolov11_detector_node:
  ros__parameters:
    image_topic: /camera1/rs1/color/image_raw
    detected_image_topic: yolo_detector/detected_image
    detected_bboxes_topic: yolo_detector/detected_bounding_boxes
    inference_time_topic: yolo_detector/yolo_time
    weights_path: weights/yolo11n.pt
    class_names_path: config/coco.names
    target_classes: [person]
    timer_period_sec: 0.033
    inference_size: 352
    queue_size: 10

# yolo_detector_node:
#   ros__parameters:
#     image_topic: /camera1/rs1/color/image_raw
#     detected_image_topic: yolo_detector/detected_image
#     detected_bboxes_topic: yolo_detector/detected_bounding_boxes
#     inference_time_topic: yolo_detector/yolo_time
#     weights_path: weights/weight_AP05:0.253207_280-epoch.pth
#     class_names_path: config/coco.names
#     target_classes: [person]
#     timer_period_sec: 0.033
#     inference_size: 352
#     queue_size: 10
#     score_threshold: 0.65